feat: Registra vehículo
ISPP-AparkApp/aparkapp-frontend pull request #82
Opened 2022-04-11 11:50 UTC by manmogvil

Se ha realizado el registro de vehículo además
de los test relativos a esta funcionalidad.

2022-04-11 21:13 UTC, ferherque requested changes
Se ha probado a añadir un vehículo y se han comprobado todas las validaciones. Lo único que habría que cambiar es la etiqueta "Segmento" por "Tamaño" (en añadir vehículo y también en editar)

2022-04-13 08:39 UTC, ferherque approved these changes
Comprobados los cambios

2022-04-13 09:01 UTC, maribelrb22 reviewed
Todo correcto, solo quitar el console.log de la marca del vehículo

2022-04-13 09:12 UTC, maribelrb22 approved these changes
Comprobados cambios

2022-04-13 09:14 UTC, merged