Activity history
ISPP-AparkApp/aparkapp-frontend pull request #94
Opened 2022-04-21 10:51 UTC by maribelrb22

2022-04-24 07:44 UTC, Jesusjbs requested changes
Hay una reserva en curso. Sin embargo, si aplico todos los filtros disponibles para reserva o para anuncios y reservas a la vez, es decir, como si no aplicara ninguno, no aparece, tengo que darle a mostrar todos.

2022-04-24 16:19 UTC, Jesusjbs approved these changes

2022-04-24 16:27 UTC, ferherque requested changes
Actualmente cuando un anuncio está libre, no se puede ni editar ni cancelar porque no aparecen los botones correspondientes. También hay dos ifs duplicados a la hora de definir el activityStatus. Concretamente el que lo define como "No realizado"

2022-04-24 18:04 UTC, ferherque requested changes
En un anuncio cancelado por el demandante aparece "Cancelado", al igual que cuando la cancela el propio ofertante. Queda mejor un estado "Cancelado por el demandante".

2022-04-26 09:29 UTC, manmogvil approved these changes

2022-04-26 09:30 UTC, Jesusjbs approved these changes

2022-04-26 11:43 UTC, merged