Adds username
ISPP-AparkApp/aparkapp-frontend pull request #96
Opened 2022-04-23 09:24 UTC by maribelrb22

2022-04-23 09:45 UTC, javivm17 approved these changes
Bien

2022-04-23 09:49 UTC, manmogvil approved these changes

2022-04-25 23:34 UTC, Javitoox requested changes
Resolver los conflictos

2022-04-26 09:40 UTC, Javitoox approved these changes

2022-04-26 09:40 UTC, merged