Añade términos y condiciones
ISPP-AparkApp/aparkapp-frontend pull request #97
Opened 2022-04-23 09:35 UTC by maribelrb22

2022-04-23 09:48 UTC, javivm17 approved these changes

2022-04-23 09:58 UTC, manmogvil requested changes
Añadir los términos y condiciones en el footer o al menos en la página principal

2022-04-23 16:21 UTC, manmogvil approved these changes

2022-04-23 17:13 UTC, maribelrb22 commented
Los cambios solicitados se encuentran en la pr #99

2022-04-24 15:21 UTC, javivm17 approved these changes

2022-04-24 15:22 UTC, javivm17 approved these changes

2022-04-25 19:13 UTC, merged